export default {
  'a_cazzo_di_cane': 'A cazzo di cane - Renè',
  'magari_mori': 'Magari Mori - Biascica',
  'sticazzi': 'Sticazzi - Martellone',
  'bucio_de_culo': 'Bucio de culo - Martellone',
  'mito': 'Mito, Genio - Renè',
  'testa_di_cazzo_senza_pari': 'Testa di cazzo - Lopez',
  'crucchi_demmerda': 'Crucchi demmerda - Renè',
  'muto': 'Muto - Biascica',
  'dai_dai_dai': 'Dai, Dai, Dai - Renè',
  'qualita': 'La qualità c\'ha rotto er cazzo - Renè',
  'italiano': 'Sei Molto Italiano - Stanis',
  'toscani': 'Toscani - Stanis',
  'attaccati_ar_cazzo': 'Attaccati al cazzo - Martellone',
  'apri_tutto': 'Apri tutto - Duccio',
  'cagna_maledetta': 'Cagna maledetta - Renè',
  'ce_se_capisce': 'Ce se capisce e \'nce se capisce - Sergio',
  'ma_tu_chi_cazzo_sei': 'Ma tu chi cazzo sei? - Stanis',
  'rompere_i_coglioni': 'Non mi devi rompere i coglioni - Arianna',
  'se_me_vedi_distratto': 'Se me vedi distratto... - Biascica',
  're_della_merda': 'Io sono il re della merda - Renè',
  'stocazzo': 'È stato stocazzo - Karin'
}